# Generated by Django 4.2.16 on 2024-10-29 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Meuble mado', max_length=100)),
                ('statut', models.CharField(choices=[('Disponible', 'Disponible'), ('Vendu', 'Vendu')], max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('couleurs', models.CharField(max_length=500)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=800)),
                ('longueur', models.DecimalField(decimal_places=0, max_digits=10)),
                ('profondeur', models.DecimalField(decimal_places=0, max_digits=10)),
                ('hauteur', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
