# Generated by Django 4.2.16 on 2024-10-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FabiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuble',
            name='couleurs',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='meuble',
            name='description',
            field=models.CharField(max_length=1200),
        ),
    ]
