# Generated by Django 4.2.16 on 2024-11-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FabiApp', '0003_meuble_photocouverture_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuble',
            name='photoCouverture',
            field=models.ImageField(default='media/couvertures/couv_defaut', upload_to='couvertures/'),
        ),
    ]
