# Generated by Django 4.2.16 on 2024-11-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FabiApp', '0004_alter_meuble_photocouverture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuble',
            name='photoCouverture',
            field=models.ImageField(default='media/couvertures/couv_defaut.jpg', upload_to='media/couvertures/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media/photos/'),
        ),
    ]
