# Generated by Django 4.2.16 on 2024-11-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FabiApp', '0005_alter_meuble_photocouverture_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuble',
            name='photoCouverture',
            field=models.ImageField(default='couvertures/couv_defaut.jpg', upload_to='couvertures/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
