# Generated by Django 4.2.16 on 2024-09-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostgreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Liste par défaut', max_length=200)),
            ],
        ),
    ]
