# Generated by Django 4.2.16 on 2024-09-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostgreApp', '0004_alter_louis_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='louis_test',
            name='name',
            field=models.CharField(default='Prénom', max_length=200),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='name',
            field=models.CharField(default='Nom_de_la_liste', max_length=200),
        ),
    ]
