# Generated by Django 4.2.16 on 2024-10-02 15:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoUserProfile',
            new_name='UserProfile',
        ),
    ]
